### ISSUE TITLE
Error causing game not to start. 

### ISSUE THREAD

**Issue by KoEOwner** [squeek502/AppleSkin#110]
Hello, 
I am having this error: 
`[11:35:22] [main/INFO]: Sodium has been successfully discovered and initialized -- your game is now faster!
[11:35:25] [main/INFO]: [STDERR]: Failed to start Minecraft:
[11:35:25] [main/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[11:35:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:35:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:35:25] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:35:25] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:35:25] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[11:35:25] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[11:35:25] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[11:35:25] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[11:35:25] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[11:35:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[11:35:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[11:35:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[11:35:25] [main/INFO]: [STDERR]: 	... 8 more
[11:35:25] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[11:35:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:35:25] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:35:25] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:35:25] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:35:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[11:35:25] [main/INFO]: [STDERR]: 	... 10 more
[11:35:25] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[11:35:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[11:35:25] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[11:35:25] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:35:25] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:185)
[11:35:25] [main/INFO]: [STDERR]: 	... 15 more
[11:35:25] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method renderTooltipCB(Lnet/minecraft/class_4587;Ljava/util/List;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIII)V in appleskin.mixins.json:GuiMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap appleskin-refmap.json
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[11:35:25] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[11:35:25] [main/INFO]: [STDERR]: 	... 22 more
[11:35:25] [main/INFO]: [STDOUT]: Exiting with -1
2021-06-07 11:35:25,675 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger` 
when trying to start up a brand new installation. It appears `appleskin-refmap.json` is not being generated for some reason. Is this an issue on my side? I can provide the other mods I have installed, although there are no obvious compatibility issues: 

>Boosted Brightness
>Fabric API,
>Giselbaers Durability Viewer,
>Item Scroller,
>Litematica,
>MaLiLib,
>Shulker Box Tooltip,
>Simple Zoom,
>Sodium

Any ideas as to what is happening? Any help is appreciated!

**Comment by squeek502** [comment]
What version of Minecraft are you playing? What verison of the mod are you using? Does it work if you *only* have AppleSkin (and Fabric API) installed?

FYI the relevant error seems to be:
```
Critical injection failure: Callback method renderTooltipCB(Lnet/minecraft/class_4587;Ljava/util/List;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIII)V in appleskin.mixins.json:GuiMixin failed injection check
```

**Comment by KoEOwner** [comment]
I am using version 1.16.5, and the latest release (appleskin-mc1.16-fabric-1.0.11). It does not work with only Appleskin and Fabric API.

**Comment by squeek502** [comment]
Can't reproduce this crash. Tried with:

- Minecraft 1.16.5 + Fabric Loader 0.11.3
- fabric-api-0.34.6+1.16
- appleskin-mc1.16-fabric-1.0.11

**Comment by KoEOwner** [comment]
I am using the most up to date versions of everything, and using the MultiMC launcher. I have not fiddled around with any of the settings (except for RAM). Is there a way I could provide more info about what may be causing it? I've also made sure my Java is the most up to date as well.

**Comment by squeek502** [comment]
Not sure what's different, I'm using the same setup with MultiMC. Maybe upload the full crash log to https://pastebin.com/ ?

**Comment by KoEOwner** [comment]
Here is the full crashlog: https://paste.dedimc.io/avuxahaboh.sql . Thank you!

**Comment by squeek502** [comment]
Looks like you have an older AppleSkin version being loaded: `appleskin-mc1.16-fabric-1.0.9`

**Comment by KoEOwner** [comment]
Hmm, I could've sworn I downloaded the latest file. Extremely sorry for wasting your time, but thank you for helping me fix it!
