### ISSUE TITLE
Potential incompatibility with latest REI

### ISSUE THREAD

**Issue by squeek502** [squeek502/AppleSkin#145]
From Curseforge:

> Thank you for everything. I found a crash that is related to Roughly Enough Items. I already reported it to the creator of Roughly Enough Items, and they asked me to report it to you too, because they believe that REI is having issues with AppleSkin.
>
> I found a crash on Roughly Enough Items (Fabric) RoughlyEnoughItems-6.0.287-alpha This crash happens in the latest RoughlyEnoughItems-6.0.298-alpha too. My friend gets the same crash too. I was just flipping through the pages of items on Roughly enough items when I crashed. My friend says she crashes when she searches for iron. Both of us get the"Index out of bounds" error.
>
> Here's both crash report and latest logs:
>
> https://drive.google.com/file/d/1cq2c6hIbKJ2YQv5e05k4nXxBfysvvATM/view?usp=sharing

The crash:

```
java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 5
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.set(ArrayList.java:441)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplImpl.handler$fcb000$onRenderTooltip(ScreenOverlayImplImpl.java:538)
	at me.shedaniel.rei.impl.client.gui.fabric.ScreenOverlayImplImpl.renderTooltipInner(ScreenOverlayImplImpl.java:60)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltipInner(ScreenOverlayImpl.java)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderTooltip(ScreenOverlayImpl.java:546)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lateRender(ScreenOverlayImpl.java:533)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$19(RoughlyEnoughItemsCoreClient.java:330)
	at net.minecraft.class_757.handler$zdg000$renderScreenPost(class_757.java:2039)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

My guess would be this is coming from [the gymnastics we're doing to inject our custom tooltip rendering](https://github.com/squeek502/AppleSkin/blob/0ed75668eb5fed674ee7809449f2ec29a20a5d97/java/squeek/appleskin/mixin/ScreenMixin.java#L22-L40). It's possible that addressing https://github.com/squeek502/AppleSkin/issues/132 might fix this too, if https://github.com/FabricMC/Mixin/pull/51 is included in a Fabric release.

**Comment by squeek502** [comment]
Should be fixed in v2.2.0
