### ISSUE TITLE
Modded server crashing due to tessellating indigo renderer 

### ISSUE THREAD

**Issue by Arkangel21203** [squeek502/AppleSkin#204]
My modded Minecraft server has been crashing for me almost every five minutes due to "Tessellating indigo renderer" or "liquid". There are 104 Mods so it could be any of them, research into the issue points to optifine but we dont have that installed. My only remaining lead is a line from Appleskins files that mention both indigo and tessellating. Can anyone provide any help? and if its not appleskin point me in the right direction? im Desperate. Crash log blow: (Most recent one says liquid, prior one was indigo) 

Description: Tesselating liquid in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26164(net.minecraft.class_6862)" because the return value of "net.minecraft.class_638.method_8320(net.minecraft.class_2338)" is null
	at net.minecraft.class_638.localvar$fda000$sandwichable$setWaterColorBlended(class_638.java:6629)
	at net.minecraft.class_638.method_23780(class_638.java:798)
	at net.minecraft.class_638.method_38535(class_638.java:114)
	at net.minecraft.class_4700.method_23770(class_4700.java:91)
	at net.minecraft.class_638.method_23752(class_638.java:778)
	at net.minecraft.class_853.method_23752(class_853.java:67)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4961(class_1163.java:26)
	at net.minecraft.class_775.method_3347(class_775.java:73)
	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl.renderFluid(FluidRenderHandlerRegistryImpl.java:124)
	at net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler.renderFluid(FluidRenderHandler.java:87)
	at net.minecraft.class_775.tessellateViaHandler(class_775.java:594)
	at net.minecraft.class_775.handler$cpa000$tesselate(class_775.java:568)
	at net.minecraft.class_775.method_3347(class_775.java)
	at net.minecraft.class_776.method_3352(class_776.java:75)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:565)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:488)
	at net.minecraft.class_846.method_22757(class_846.java:139)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_638.localvar$fda000$sandwichable$setWaterColorBlended(class_638.java:6629)
	at net.minecraft.class_638.method_23780(class_638.java:798)
	at net.minecraft.class_638.method_38535(class_638.java:114)
	at net.minecraft.class_4700.method_23770(class_4700.java:91)
	at net.minecraft.class_638.method_23752(class_638.java:778)
	at net.minecraft.class_853.method_23752(class_853.java:67)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4961(class_1163.java:26)
	at net.minecraft.class_775.method_3347(class_775.java:73)
	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl.renderFluid(FluidRenderHandlerRegistryImpl.java:124)
	at net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler.renderFluid(FluidRenderHandler.java:87)
	at net.minecraft.class_775.tessellateViaHandler(class_775.java:594)
	at net.minecraft.class_775.handler$cpa000$tesselate(class_775.java:568)
	at net.minecraft.class_775.method_3347(class_775.java)
	at net.minecraft.class_776.method_3352(class_776.java:75)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:565)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:488)

-- Block being tesselated --
Details:
	Block location: World: (-113,61,-92), Section: (at 15,13,4 in -8,3,-6; chunk contains blocks -128,-64,-96 to -113,319,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.class_776.method_3352(class_776.java:75)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:565)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:488)
	at net.minecraft.class_846.method_22757(class_846.java:139)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 1 total; [class_746['Arkangel18'/29418, l='ClientLevel', x=30.59, y=64.05, z=34.52]]
	Chunk stats: 5041, 585
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,63,-5), Section: (at 0,15,11 in 2,3,-1; chunk contains blocks 32,-64,-16 to 47,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 1707285 game time, 1363454 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_43589(class_310.java:822)
	at net.minecraft.class_310.method_1514(class_310.java:723)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, spoornpacks, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3037685712 bytes (2896 MiB) / 4890558464 bytes (4664 MiB) up to 9227468800 bytes (8800 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1338
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2560
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1272
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25854.79
	Virtual memory used (MB): 20506.07
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 508.59
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8800m -Xms256m
	Fabric Mods: 
		additionalstructures: Additional Structures 4.0.0
		advancednetherite: Advanced Netherite 1.6.4-1.19.2
		adventurez: AdventureZ 1.4.14
		alloy_forgery: Alloy Forgery 2.0.15+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 5.12.42
		arclight: Arclight 0.1.0a-1.19
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		artifacts: Artifacts 7.1.1+fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 15.1.3
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.3
		backpackmod: Backpack Mod 4.0.5
		bclib: BCLib 2.0.20
		besmirchment: Besmirchment 1.19-2
			playerabilitylib: Pal 1.6.0
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		betterend: Better End 2.0.11
		betternether: Better Nether 7.0.9
		bewitchment: Bewitchment 1.19-4
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.6.1
			midnightlib: MidnightLib 0.5.2
		bns: Brok N Sindri's Trinkets 1.1.1
		bookshelf: Bookshelf 14.2.10
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bwplus: Bewitchment Plus 1.19-4
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		charmofundying: Charm of Undying 6.0.0+1.19.2
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.0.75
		clumps: Clumps 9.0.0+7
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		comforts: Comforts 6.0.0+1.19.2
			spectrelib: SpectreLib 0.8.1+1.19
		dragonloot: DragonLoot 1.1.1
		dualwielding: Dual Wielding 1.1.2
		dungeon_now_loading: dungeon-now-loading-17-1 1.0.0
		dungeons_arise: When Dungeons Arise 2.1.51
		edenring: EdenRing 0.6.3
		enchdesc: EnchantmentDescriptions 11.1.9
		endgoblintraders: End Goblin Traders 1.5.1
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		explorerscompass: Explorer's Compass 1.19-2.1.2-fabric
		extended_armor_bars: Extended Armor Bars 1.2.1
		extra_classes_origins: Extra Classes - Origins 1.0.0
		extraalchemy: Extra Alchemy 1.8.3
		extraorigins: Extra Origins 1.19-2
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		farmersdelight: Farmer's Delight 1.19-1.3.1
		farsight: Farsight Mod 1.19-2.0
		forgeconfigapiport: Forge Config API Port 4.0.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendlyfire: FriendlyFire 12.0.2
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 1.10
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		healingcampfire-fabric: Healing Campfire (Fabric) 3.5
		heartytrinkets: Hearty Trinkets 1.19-1.0.0
		iceberg: Iceberg 1.0.46
		infusion_table: Infusion Table 1.1.0
		jade: Jade 7.7.1
		jamlib: JamLib 0.4.2
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.1.1.239
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		legendarytooltips: Legendary Tooltips 1.2.6
		levelz: LevelZ 1.3.6
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 2.0.0
		lithium: Lithium 0.8.1
		lovely_snails: Lovely Snails 1.1.0+1.19
		medievalentity: Mediaval Entity 2.0.2
		medievalmusic: Medieval Music Mod 1.19-1.8
		medievalorigins: Medieval Origins 1.19.x-4.1.3
		medievalweapons: Medieval Weapons 1.2.1
		minecraft: Minecraft 1.19
		mobhealthbar: MobHealthBar 2.1.0
		moborigins: Mob Origins 1.9.0
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.4
		mousetweaks: Mouse Tweaks 2.22
		myloot: myLoot 3.0.1-1.19.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		mythicmounts: Mythic Mounts 1.19-7.0
		naturalist: Naturalist 2.1.0
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
		origins-classes: Origins: Classes 1.4.0
		owo: oωo 0.7.3+1.19
		oxidized: Oxidized 1.7.1
		patchouli: Patchouli 1.19-74-FABRIC
		pehkui: Pehkui 3.4.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		rare-ice: Rare Ice 0.5.0
		rightclickharvest: Right Click Harvest 3.0.0
		ringsofascension: Rings of Ascension 1.0
		sandwichable: Sandwichable 1.3.a+1.19
		sextant: Immersive Travel Overhaul 1.2
		spark: spark 1.9.26
		splatus_ultris: Ultris: Boss Expansion 5.6.4
		spoornpacks: SpoornPacks 4.3.1-1.19
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.1
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.1
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.1
		stoneholm: Stoneholm 1.4.4
		t_and_t: Towns and Towers - Structure Add-on 1.8
		things: Things 0.2.19+1.19
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		trinkets: Trinkets 3.4.0
		wandering_collector: Wandering Collector 1.1.3+mc1.19
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		weaponmaster: YDM's Weapon Master 3.0.0 
		whisperwoods: Whisperwoods 1.19-2.1.1
		wunderreich: Wunderreich 3.0.15
	Launched Version: fabric-loader-0.14.9-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.72, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, spoornpacks, Fabric Mods
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

**Comment by squeek502** [comment]
I see a `$sandwichable$setWaterColorBlended` in the stack trace. Might be worth testing if removing Sandwichable stops the crash.

**Comment by Arkangel21203** [comment]
I deleted sandwichable on curse forge and server files but thats always there when the game crashed like it still does.

**Comment by squeek502** [comment]
Does it stop crashing if you remove AppleSkin?

If all else fails, as long as you can reproduce the crash consistently, you can try a [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm):

- Remove half of your installed mods and see if the crash still happens
- If the crash still happens, then remove half again and repeat until it stops happening
- If the crash is no longer happening, then you know the mod causing the problem is in the set of mods that you just removed, so uninstall everything else and re-install only that set and then restart the process (remove half, etc)

You'll eventually end up with exactly one mod that you then know is causing the problem (unless it's a combination of mods, but this technique can work for figuring that out too).

**Comment by SAGESSE-CN** [comment]
It seems to be a collapse caused by rendering some liquid.

modify the coordinates of your login to determine whether the crash caused by the content on the world or on the player

**Comment by Arkangel21203** [comment]
I believe it to be a player. Always a different location and others on the server were not suffering this
