### ISSUE TITLE
Crashing when start game

### ISSUE THREAD

**Issue by tuss04** [squeek502/AppleSkin#205]
It's crashing my game on start :(

This is my log: 

`-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD appleskin --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
		at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:92) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at squeek.appleskin.network.SyncHandler.init(SyncHandler.java:33) ~[appleskin-forge-mc1.19-2.4.0.jar%23147!/:2.4.0+mc1.19] {re:classloading}
		at squeek.appleskin.AppleSkin.preInit(AppleSkin.java:38) ~[appleskin-forge-mc1.19-2.4.0.jar%23147!/:2.4.0+mc1.19] {re:classloading}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.0.111.jar%23178!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.0.111.jar%23177!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/Tusso4/AppData/Roaming/.minecraft/mods/appleskin-forge-mc1.19-2.4.0.jar
	Failure message: AppleSkin (appleskin) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent
	Mod Version: 2.4.0+mc1.19
	Mod Issue URL: https://github.com/squeek502/AppleSkin
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:92) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at squeek.appleskin.network.SyncHandler.init(SyncHandler.java:33) ~[appleskin-forge-mc1.19-2.4.0.jar%23147!/:2.4.0+mc1.19] {re:classloading}
	at squeek.appleskin.AppleSkin.preInit(AppleSkin.java:38) ~[appleskin-forge-mc1.19-2.4.0.jar%23147!/:2.4.0+mc1.19] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.0.111.jar%23178!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19-41.0.111.jar%23177!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 637342640 bytes (607 MiB) / 1677721600 bytes (1600 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f06
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7196
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32190,73
	Virtual memory used (MB): 15022,89
	Swap memory total (MB): 15872,00
	Swap memory used (MB): 162,63
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19_HD_U_H9
	OptiFine Build: 20220731-224510
	Render Distance Chunks: 12
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.32+High-MB.zip
	OpenGlVersion: 3.2.0 NVIDIA 471.96
	OpenGlRenderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.111.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		voicechat-forge-1.19-2.2.52 (2).jar               |Simple Voice Chat             |voicechat                     |1.19-2.2.52         |SIDED_SETU|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |SIDED_SETU|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.1_mc1.19 (1).jar         |Ambient Sounds                |ambientsounds                 |5.2.1               |SIDED_SETU|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.7.4_mc1.19.jar              |CreativeCore                  |creativecore                  |2.7.4               |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.19.1-forge-11.2.0.241.jar                   |Just Enough Items             |jei                           |11.2.0.241          |SIDED_SETU|Manifest: NOSIGNATURE
		EyesInTheDarkness-1.19-1.3.5.jar                  |Eyes in the Darkness          |eyesinthedarkness             |1.3.5               |SIDED_SETU|Manifest: NOSIGNATURE
		goblintraders-1.7.3-1.19.jar                      |Goblin Traders                |goblintraders                 |1.7.3               |SIDED_SETU|Manifest: NOSIGNATURE
		reap-1.19-1.0.1.jar                               |Reap Mod                      |reap                          |1.19-1.0.1          |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.19-5.1.0.4.jar                     |Curios API                    |curios                        |1.19-5.1.0.4        |SIDED_SETU|Manifest: NOSIGNATURE
		Patchouli-1.19-75.jar                             |Patchouli                     |patchouli                     |1.19-75             |SIDED_SETU|Manifest: NOSIGNATURE
		Neat-1.8-31.jar                                   |Neat                          |neat                          |1.8-31              |SIDED_SETU|Manifest: NOSIGNATURE
		journeymap-1.19-5.8.5-forge.jar                   |Journeymap                    |journeymap                    |5.8.5               |SIDED_SETU|Manifest: NOSIGNATURE
		[1.19]+SecurityCraft+v1.9.3.jar                   |SecurityCraft                 |securitycraft                 |1.9.3               |SIDED_SETU|Manifest: NOSIGNATURE
		TravelersBackpack-1.19-8.0.8.jar                  |Traveler's Backpack           |travelersbackpack             |8.0.8               |SIDED_SETU|Manifest: NOSIGNATURE
		LibX-1.19-4.0.7.jar                               |LibX                          |libx                          |1.19-4.0.7          |SIDED_SETU|Manifest: NOSIGNATURE
		MoreVanillaTools-1.19-5.0.3.jar                   |MoreVanillaTools              |morevanillatools              |1.19-5.0.3          |SIDED_SETU|Manifest: NOSIGNATURE
		elevatorid-1.19-1.8.6.jar                         |Elevator Mod                  |elevatorid                    |1.19-1.8.6          |SIDED_SETU|Manifest: NOSIGNATURE
		InventoryHud_[1.19].forge-3.4.6.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.6               |SIDED_SETU|Manifest: NOSIGNATURE
		tombstone-8.0.4-1.19.jar                          |Corail Tombstone              |tombstone                     |8.0.4               |SIDED_SETU|Manifest: NOSIGNATURE
		DungeonCrawl-1.19-2.3.11.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.11              |SIDED_SETU|Manifest: NOSIGNATURE
		worldedit-mod-7.2.11-beta-01.jar                  |WorldEdit                     |worldedit                     |7.2.11-beta-01+6200-|SIDED_SETU|Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.7.jar    |Oh The Biomes You'll Go       |byg                           |2.0.0.7             |SIDED_SETU|Manifest: NOSIGNATURE
		FallingTree-1.19-3.7.4.jar                        |FallingTree                   |fallingtree                   |3.7.4               |SIDED_SETU|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		3dskinlayers-forge-1.5.1-mc1.19.1.jar             |3dSkinLayers                  |skinlayers3d                  |1.5.1               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.19-41.0.111-universal.jar                 |Forge                         |forge                         |41.0.111            |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.19        |ERROR     |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.12.jar                    |GeckoLib                      |geckolib3                     |3.1.12              |SIDED_SETU|Manifest: NOSIGNATURE
		ars_nouveau-1.19.0-3.1.1.jar                      |Ars Nouveau                   |ars_nouveau                   |3.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		structure_gel-1.19-2.5.4.jar                      |Structure Gel API             |structure_gel                 |2.5.4               |SIDED_SETU|Manifest: NOSIGNATURE
		DungeonsArise-1.19-2.1.51-beta.jar                |When Dungeons Arise           |dungeons_arise                |2.1.51              |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 2b320504-b3b0-4080-9eed-ecc7b8dec5db
	FML: 41.0
	Forge: net.minecraftforge:41.0.111`

**Comment by squeek502** [comment]
Update your AppleSkin, you need AppleSkin v2.4.2 for Forge >= 41.0.94: https://www.curseforge.com/minecraft/mc-mods/appleskin/files/3872808
