### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by JaTiTV** [squeek502/AppleSkin#218]

**Comment by SAGESSE-CN** [comment]
@squeek502 not need any changes.

forge:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/206892820-d20e59f3-c903-457e-b593-9b141304d86c.png">

fabric:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/206892757-96032998-26ae-4fed-919a-a293837a8428.png">

forge by [appleskin-forge-mc1.19-2.4.2.jar](https://www.curseforge.com/minecraft/mc-mods/appleskin/files/3872808)
fabric by [appleskin-fabric-mc1.19-2.4.1.jar](https://www.curseforge.com/minecraft/mc-mods/appleskin/files/3927567)

**Comment by SAGESSE-CN** [comment]
correction, some breaking changes in fabric
```
[16:24:33] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1293.method_5593()'
	at squeek.appleskin.helpers.FoodHelper.getEstimatedHealthIncrement(FoodHelper.java:103) ~[appleskin-fabric-mc1.19-2.4.1.jar:?]
	at squeek.appleskin.client.HUDOverlayHandler.onRender(HUDOverlayHandler.java:133) ~[appleskin-fabric-mc1.19-2.4.1.jar:?]
	at net.minecraft.class_329.handler$zzc000$renderFoodPost(class_329.java:1494) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1760(class_329.java:900) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:910) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1193) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.11-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.11-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.11.jar:?]
```

**Comment by squeek502** [comment]
I think that crash is from the removal of `isPermanent` from `StatusEffect`, I've fixed that for Fabric in https://github.com/squeek502/AppleSkin/commit/61ff4c8bf928c2822506ccedb48f0e7ab8784013 but haven't been able to test/release it. Will likely need the same fix for the Forge version.

**Comment by SAGESSE-CN** [comment]
forge not this issue, because it doesn't use the method

**Comment by squeek502** [comment]
Done, only the Fabric version needed an update: https://www.curseforge.com/minecraft/mc-mods/appleskin/files/4171199
