### ISSUE TITLE
Survival Crash to Desktop with ArmorPoints++ on Fabric 1.20 

### ISSUE THREAD

**Issue by Satomilee** [squeek502/AppleSkin#244]
Crashes when loading into a survival world with ArmorPoints++ and AppleSkin installed together

`java.lang.NoSuchMethodError: 'void squeek.appleskin.client.HUDOverlayHandler.onPreRender(net.minecraft.class_4587)'
	at dev.cheos.armorpointspp.compat.AppleskinSafeAccess.handlerOnPreRender(AppleskinSafeAccess.java:9)
	at dev.cheos.armorpointspp.ApppGui.renderFood(ApppGui.java:164)
	at dev.cheos.armorpointspp.ApppGui.method_1760(ApppGui.java:67)
	at net.minecraft.class_329.method_1753(class_329.java:214)
	at dev.cheos.armorpointspp.ApppGui.method_1753(ApppGui.java:41)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

Minecraft | 1.20
Fabric | 0.14.21
AppleSkin | 2.5.0
Armor Points++ | 3.1.0

**Comment by Satomilee** [comment]
[https://modrinth.com/mod/armorpoints/version/fabric-1.20-3.1.0](url)

Looks like this is an issue on Armor Points end and not Appleskin

**Comment by SAGESSE-CN** [comment]
yep, because the api this changed

**Comment by Zorklis** [comment]
same reason for crashing autohud I think
