### ISSUE TITLE
Config doesn't save

### ISSUE THREAD

**Issue by rbits0** [squeek502/AppleSkin#250]
I change the settings of AppleSkin, and it works, but doesn't save a config file, so if I close and reopen the game, my settings are reset.

Minecraft 1.20.1
Quilt Loader 0.19.2
AppleSkin 2.5.0+mc1.20

**Comment by rbits0** [comment]
```
[21:00:13] [Render thread/ERROR]: Failed to save config 'class squeek.appleskin.ModConfig'
me.shedaniel.autoconfig.serializer.ConfigSerializer$SerializationException: java.nio.file.FileAlreadyExistsException: /home/riley/.local/share/PrismLauncher/instances/Quilt/.minecraft/config
	at me.shedaniel.autoconfig.serializer.JanksonConfigSerializer.serialize(JanksonConfigSerializer.java:65) ~[transformed-mod-cloth-config.i0:0/:?]
	at me.shedaniel.autoconfig.ConfigManager.save(ConfigManager.java:83) ~[transformed-mod-cloth-config.i0:0/:?]
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:54) ~[transformed-mod-cloth-config.i0:0/:?]
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[transformed-mod-cloth-config.i0:0/:?]
	at squeek.appleskin.ModConfig.init(ModConfig.java:20) ~[transformed-mod-appleskin.i0:0/:?]
	at squeek.appleskin.AppleSkin.onInitializeClient(AppleSkin.java:21) ~[transformed-mod-appleskin.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:56) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:56) ~[quilt-loader-0.19.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.nio.file.FileAlreadyExistsException: /home/riley/.local/share/PrismLauncher/instances/Quilt/.minecraft/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:753) ~[?:?]
	at me.shedaniel.autoconfig.serializer.JanksonConfigSerializer.serialize(JanksonConfigSerializer.java:60) ~[transformed-mod-cloth-config.i0:0/:?]
	... 23 more
```

**Comment by squeek502** [comment]
Can't reproduce this with:

Minecraft 1.20.1
Quilt Loader 0.19.2
AppleSkin 2.5.0+mc1.20
modmenu-7.1.0
qfapi-7.0.6_qsl-6.0.4_fapi-0.85.0_mc-1.20.1
