### ISSUE TITLE
Crash: Exception caught during firing event: Payload {} may not be sent to the client!

### ISSUE THREAD

**Issue by Kirkezz** [squeek502/AppleSkin#330]
```
[06Oct2024 10:50:41.568] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Apelsyn1509 joined the game
[06Oct2024 10:50:41.611] [Server thread/ERROR] [net.neoforged.bus.EventBus/EVENTBUS]: Exception caught during firing event: Payload {} may not be sent to the client!
	Index: 0
	Listeners:
		0: @SubscribeEvent: squeek.appleskin.network.SyncHandler@69db539 onLivingTickEvent(Lnet/neoforged/neoforge/event/tick/EntityTickEvent$Pre;)V
java.lang.UnsupportedOperationException: Payload {} may not be sent to the client!
	at TRANSFORMER/neoforge@20.6.121/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:441)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:167)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:162)
	at TRANSFORMER/neoforge@20.6.121/net.neoforged.neoforge.network.PacketDistributor.sendToPlayer(PacketDistributor.java:51)
	at TRANSFORMER/appleskin@3.0.5+mc1.20.5/squeek.appleskin.network.SyncHandler.onLivingTickEvent(SyncHandler.java:53)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:49)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/neoforge@20.6.121/net.neoforged.neoforge.event.EventHooks.fireEntityTickPre(EventHooks.java:924)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:770)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.world.level.Level.guardEntityTick(Level.java:556)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:417)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:397)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1013)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:313)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701)
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[06Oct2024 10:50:42.438] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1017) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:313) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:893) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:261) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsupportedOperationException: Payload {} may not be sent to the client!
	at TRANSFORMER/neoforge@20.6.121/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:441) ~[neoforge-20.6.121-universal.jar%23130!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:167) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:162) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/neoforge@20.6.121/net.neoforged.neoforge.network.PacketDistributor.sendToPlayer(PacketDistributor.java:51) ~[neoforge-20.6.121-universal.jar%23130!/:?]
	at TRANSFORMER/appleskin@3.0.5+mc1.20.5/squeek.appleskin.network.SyncHandler.onLivingTickEvent(SyncHandler.java:53) ~[appleskin-neoforge-mc1.20.5-3.0.5.jar%23132!/:3.0.5+mc1.20.5]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:49) ~[bus-8.0.1.jar%2368!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%2368!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%2368!/:?]
	at TRANSFORMER/neoforge@20.6.121/net.neoforged.neoforge.event.EventHooks.fireEntityTickPre(EventHooks.java:924) ~[neoforge-20.6.121-universal.jar%23130!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:770) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.world.level.Level.guardEntityTick(Level.java:556) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:417) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:397) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1013) ~[server-1.20.6-20240429.153634-srg.jar%23129!/:?]
	... 5 more
[06Oct2024 10:50:42.452] [Server thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 7a7b683e-f24a-4d18-adcb-16018cf89e4e
[06Oct2024 10:50:42.452] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /root/server/./crash-reports/crash-2024-10-06_10.50.42-server.txt
[06Oct2024 10:50:42.453] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[06Oct2024 10:50:42.454] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[06Oct2024 10:50:42.501] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Igorantivirus lost connection: Server closed
[06Oct2024 10:50:42.502] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Igorantivirus left the game
[06Oct2024 10:50:42.505] [Server thread/INFO] [voicechat/]: [voicechat] Disconnecting client Igorantivirus
[06Oct2024 10:50:42.514] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Eclaytt lost connection: Server closed
[06Oct2024 10:50:42.516] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Eclaytt left the game
[06Oct2024 10:50:42.517] [Server thread/INFO] [voicechat/]: [voicechat] Disconnecting client Eclaytt
[06Oct2024 10:50:42.531] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[06Oct2024 10:50:46.128] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[06Oct2024 10:50:46.419] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[06Oct2024 10:50:46.425] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[06Oct2024 10:50:46.431] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[06Oct2024 10:50:46.432] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[06Oct2024 10:50:46.432] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[06Oct2024 10:50:46.432] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[06Oct2024 10:50:46.454] [Server thread/INFO] [net.minecraft.server.rcon.thread.GenericThread/]: Thread RCON Listener stopped
```
When a new player joined, the server crashed. Server is running on 1.20.6.

**Comment by squeek502** [comment]
What version of AppleSkin?

**Comment by Kirkezz** [comment]
appleskin-neoforge-mc1.20.5-3.0.5 installed on neoforge 1.20.6 both client and server

**Comment by doewsqwe** [comment]
i got same phenomenon did you solve it?

**Comment by squeek502** [comment]
Fixed in v3.0.8
