### ISSUE TITLE
[1.21 Fabric] Crash rendering tooltips

### ISSUE THREAD

**Issue by Sollace** [squeek502/AppleSkin#331]
This came from one of my users which was getting a crash when they opened their inventory. The crashreport didn't have anything helpful, but after checking the latest.log file it seems to be coming from appleskin trying to render a tooltip for an item with no food component.

Appeskin: 3.0.5+mc.21
Minecraft: 1.21
Loader: Fabric

```
[14:10:22] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at knot/net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4174.comp_2491()" because "defaultFood" is null
	at knot/squeek.appleskin.client.TooltipOverlayHandler$FoodOverlay.<init>(TooltipOverlayHandler.java:99) ~[appleskin-fabric-mc1.21-3.0.5.jar:?]
	at knot/squeek.appleskin.client.TooltipOverlayHandler.onItemTooltip(TooltipOverlayHandler.java:182) ~[appleskin-fabric-mc1.21-3.0.5.jar:?]
	at knot/net.minecraft.class_1799.handler$zze000$appleskin$getTooltipFromItem(class_1799.java:1118) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1799.method_7950(class_1799.java:807) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25408(class_437.java:243) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.method_51454(class_465.java:187) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_465.method_2380(class_465.java:182) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_490.method_25394(class_490.java:86) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.mixinextras$bridge$method_47413$209(class_757.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.wrapOperation$zod000$fabric-screen-api-v1$onRenderScreen(class_757.java:3086) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 6 more
```

[latest.log](https://github.com/user-attachments/files/17378998/latest.log)

**Comment by Sollace** [comment]
Fixed from my side. Sorry for the inconvenience.
