### ISSUE TITLE
Mod 'AppleSkin' (appleskin) requires any version of mod fabric, which is missing!

### ISSUE THREAD

**Issue by Froosk** [squeek502/AppleSkin#81]
Using Fabric version 0.10.6+build.214 with MultiMC 5 version 0.6.11-1430 to load AppleSkin version 1.0.11 gives me an error message saying that I need to install Fabric, which is already installed. This appeared when I had multiple mods installed, so I tried disabling all of them except for AppleSkin, and the problem persisted. Even though it explicitly says that the error occurred in AppleSkin, I still tested without the mod, and the game launched fine.

This is the log:
```
[19:36:38] [main/INFO]: Loading for game Minecraft 1.16.4
[19:36:38] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'AppleSkin' (appleskin) requires any version of mod fabric, which is missing!
	 - You must install any version of fabric.
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:315) ~[fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:210) ~[fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:200) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:128) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by squeek502** [comment]
That is referring to the Fabric API. Do you have that installed?

https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by squeek502** [comment]
Going to consider this resolved unless there's more information that can be provided.
