### ISSUE TITLE
Mod loading error/Not enough data available

### ISSUE THREAD

**Issue by Lobbenator** [squeek502/AppleSkin#93]
Hello, I am apart of an SMP and we recently added this mod and it has been working great so far. However I received this crash report and can't even load into Forge Minecraft.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.2.jar:?] {}
-- MOD appleskin --
Details:
	Mod File: AppleSkin-mc1.16.2-forge-1.0.14.jar
	Failure message: AppleSkin (appleskin) has failed to load correctly
		com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	Mod Version: 1.0.14
	Mod Issue URL: https://github.com/squeek502/AppleSkin
	Exception message: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
Stacktrace:
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.2.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.2.jar:?] {}
	at squeek.appleskin.ModConfig.init(ModConfig.java:19) ~[?:1.0.14] {re:classloading}
	at squeek.appleskin.AppleSkin.<init>(AppleSkin.java:33) ~[?:1.0.14] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.0] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3098/1394526584.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3122/1619842305.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1153004472 bytes (1099 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.43.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.43.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.43
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.43-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |CREATE_REG|NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |CREATE_REG|NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |CREATE_REG|NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |CREATE_REG|NOSIGNATURE
		architectury-1.7.117-forge.jar                    |Architectury                  |architectury                  |1.7.117             |CREATE_REG|NOSIGNATURE
		ftb-gui-library-1605.2.1.39-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.39         |CREATE_REG|NOSIGNATURE
		mumblelink-1.16.5-4.6.3.jar                       |MumbleLink for Forge          |mumblelink                    |4.6.3               |CREATE_REG|NOSIGNATURE
		moreoverlays-1.18.13-mc1.16.5.jar                 |More Overlays Updated         |moreoverlays                  |1.18.13-mc1.16.5    |CREATE_REG|NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |CREATE_REG|NOSIGNATURE
		masonry-1.16.3-0.3.6.jar                          |Masonry                       |masonry                       |NONE                |CREATE_REG|NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.1.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.0.43-universal.jar                |Forge                         |forge                         |36.0.43             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |ERROR     |NOSIGNATURE
		decorative_winter-0.1.2.jar                       |Decorative Winter             |decorative_winter             |0.1.2               |CREATE_REG|NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |CREATE_REG|NOSIGNATURE
		emotecraft-0.12.4_for_MC1.16.2+.jar               |Emotecraft                    |emotecraft                    |0.12.4              |CREATE_REG|NOSIGNATURE
		Clumps-6.0.0.17.jar                               |Clumps                        |clumps                        |6.0.0.17            |CREATE_REG|NOSIGNATURE
		journeymap-1.16.5-5.7.1b3.jar                     |Journeymap                    |journeymap                    |5.7.1b3             |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 2abecf87-a3ff-4d2c-8323-2ee47bfcd205
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6
	OpenGlRenderer: Radeon RX550/550 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by squeek502** [comment]
My guess would be your AppleSkin config file is malformed or corrupted. Try deleting `config/appleskin-client.toml` if it exists and see if that fixes it.

**Comment by Lobbenator** [comment]
Thanks squeeks that worked.
